type: 
name: 
version: 
date:
kite:
  type:
  version:
  wing:
    sections:
      headers:
      data:
    airfoils:
      headers:
      data:
    structure:
      wing_particles:
        headers:
        data:
      wing_connections:
        headers:
        data:
      wing_elements:
        headers:
        data:
      structure_merged:
        wing_particles:
          headers:
          data:
        strut_tubes:
          headers:
          data:
        le_tubes:
          headers:
          data:
  fuselage:
    headers:
    data:
  tail:
    headers:
    data:
  bridle:
    version:
    bridle_point_node:
    pulley_mass:
    kcu_mass:
    bridle_particles:
      headers:
      data:
    bridle_connections:
      headers:
      data:
    bridle_lines:
      headers:
      data:
    bridle_elements:
      headers:
      data:
    merged:
      bridle_particles:
        headers:
        data:
      bridle_connections:
        headers:
        data:
      bridle_lines:
        headers:
        data:
tether:
  version:
  length:
  diameter:
  material:
  density:
  num_segments:
ground_station:
  name:
  version:
  date:
  headers:
  data:
materials:
  headers:
  data:
